### ISSUE TITLE
use industry specific market index and general carbon risk factors to identify specific stock risks

### ISSUE THREAD

**Issue by sichen1234** [opentaps/open-climate-investing#14]
When testing the model against a utility (DUK), it seems that the regression model has little explanatory power.  Could we improve it by using a specific market index (such as utility ETF fund) as the market factor and then add in the carbon risk factor?  Would that give good explanatory power to the stocks in that industry?  Would it help identify stocks with high and low carbon risks when the particular sector is not as correlated with the market as a whole?

This could be expanded to other sectors, such as airlines.

If stocks in these sectors which have high emissions output do not have carbon betas even relative to their own sectors, then the market may be saying that the companies are not vulnerable.  For example, it may believe that utilities will simply be allowed to pass through emissions taxes to their customers, and therefore the transition risk is not at the utilities but at the customers of the utilities.

**Comment by slim-patchy** [comment]
@sichen1234 It seems like this issue could be an interesting research topic, and thus warrants some careful consideration into developing a more comprehensive strategy to be used to assess such industry-specific stock risks. I would like to attempt to address this issue and will post here to follow up later.

**Comment by slim-patchy** [comment]
Some really general directions may be gleaned from a E.U. Climate Action report at https://ec.europa.eu/clima/policies/adaptation/how/sectors_en. A more in-depth look at the industries / sectors impacted can be found in [Figure 2](https://www2.deloitte.com/content/dam/insights/us/articles/43123_feeling-the-heat/figures/Fig-2.png) of a Deloitte report at https://www2.deloitte.com/us/en/insights/topics/strategy/impact-and-opportunities-of-climate-change-on-business.html. The latter is interesting in that they come from the points of view of company CFOs.
