### ISSUE TITLE
CARIMA website doesn't work

### ISSUE THREAD

**Issue by clintonTE** [opentaps/open-climate-investing#27]
Not an issue with open-climate-investing per se. 

The documentation cites  https://carima-project.de/en for accessing tools and the BMG factor, but on multiple machines I just get an SSL error trying to access the site. This makes investigation into the factor problematic.

**Comment by sichen1234** [comment]
Yes, the project is not really active.  You can look at their manual with the link in our README page -- it still works.  Other than that, we have their BMG series and the scripts to run and analyze it with here.
