### ISSUE TITLE
identify places to buy carbon offsets

### ISSUE THREAD

**Issue by sichen1234** [opentaps/open-climate-investing#28]
Find some places where we could buy carbon offsets for the [Decarbonization DAO](https://github.com/opentaps/open-climate-investing/tree/main/dao/decarbonization)

We want something like the [Gold Standard Marketplace](https://marketplace.goldstandard.org/collections/projects), where we could buy offsets from specific projects rather than generic names.  It does not have to be in crypto.

**Comment by hai-yr** [comment]
https://www.climateactionreserve.org/how/offsets-marketplace/ possibly a useful list of different marketplaces, brokers and exchanges

**Comment by sichen1234** [comment]
@hai-yr Does patch.io have a web UI, or is everything through their API?

Do they allow choosing a specific project to purchase?

Is that specified in the UI?

Do they have a list of projects available on their website?

**Comment by sichen1234** [comment]
OK this is a good start.  Thanks!
