### ISSUE TITLE
modify bulk_script.py to generate results for list of stocks

### ISSUE THREAD

**Issue by sichen1234** [opentaps/open-climate-investing#3]
Modify the bulk_script.py to generate results for list of stocks.  

It can be a list of stock tickers either in a CSV file or embedded in bulk_script.py as an array for now.  (We'll eventually hook it up to a database and backend.)  

The output can be the same as now, statistics for each stock separated by a header.

**Comment by mattbowler** [comment]
Added the Durbin-Watson (autocorrelation), Breusch-Pagan (heteroskedasticity) & Jarques-Bera (normality) statistics to the table, as well as

**Comment by sichen1234** [comment]
@mattbowler Do you think in addition to the P>|t| it would be also useful to get the t-statistics for each of the coefficients?

Also, in the attached screenshot, there are  2 rows of Jarque-Bera and Breusch-Pagan statistics, one  for the coefficients and one for the P>|t|.  What do the different numbers mean?
![Screen Shot 2021-09-07 at 3 39 13 PM](https://user-images.githubusercontent.com/1706353/132419514-8e97ca22-4be8-4382-90bb-2f0684dbe53c.png)

**Comment by mattbowler** [comment]
@sichen1234 committed the changes to include standard error & t-statistic in the output table. I also included an option to use default values

**Comment by sichen1234** [comment]
@mattbowler How do I run it with standard values?

**Comment by mattbowler** [comment]
@sichen1234 I only added that option to factor_regression.py. I have now added it to bulk_script.py. I will clean up the code so that factor_regression.py & bulk_script.py use the same user input function so that changes made are made to both

**Comment by sichen1234** [comment]
Now it works.  Thanks!
