### ISSUE TITLE
Document all stats model output fields and which ones are important 

### ISSUE THREAD

**Issue by sichen1234** [opentaps/open-climate-investing#6]
Please add in the read me file what all the fields of the stats model output mean, and which ones are important when looking at the results.

**Comment by sichen1234** [comment]
@mattbowler Could you pls put some comments in README.md about the Jarque-Bera, Breusch-Pagan, and Durbin-Watson statistics and how to interpret them?  For example take a look at the results from my stock_tickers.csv file which I posted in #3

**Comment by mattbowler** [comment]
@sichen1234 I've created definitions and interpretations of the statistics. Please check that they are understandable.

**Comment by sichen1234** [comment]
Looks good.  Thank you!
