### ISSUE TITLE
clean up code to remove error messages

### ISSUE THREAD

**Issue by mattbowler** [opentaps/open-climate-investing#7]
There are error messages being printed by underlying packages. These are not impacting the results but need to be traced and fixed in case this causes issues down the line.

**Comment by mattbowler** [comment]
Fixed the first set of errors. It is highly unlikely they would have become problematic later, but it's best to be safe.
The second set of errors come from the underlying module, so are harder to diagnose.

**Comment by mattbowler** [comment]
Second error message fixed by manually adding constant rather than using statsmodels function to do so

**Comment by sichen1234** [comment]
There are still some error messages for me -- see my latest screenshot in #3

**Comment by mattbowler** [comment]
> There are still some error messages for me -- see my latest screenshot in #3

This is a data-related issue that will be fixed in [#8](https://github.com/opentaps/open-climate-investing/issues/8)

**Comment by mattbowler** [comment]
Going to close this issue because the specific error messages are no longer showing
